### ISSUE TITLE
Cannot run with android

### ISSUE THREAD

**Issue by henrycity** [fullstackreact/FirestackApp#12]
After running these commands 
`npm install`
`react-native link`

If I run it on Genymotion, I get this error. I also test it with iOS and it does not work either.
```
google-services plugin could not detect any version for com.google.android.gms or com.google.firebase, default version: 9.0.0 will be used.
please apply google-services plugin at the bottom of the build file.

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':app'.
> Cannot evaluate module react-native-oauth : Configuration with name 'default' not found.
```

**Comment by iamkyleee** [comment]
Receiving the same error :(

**Comment by auser** [comment]
Do you have the `google-services` plugin at the bottom of the android `build.gradle`?

What's the error on ios?

**Comment by iamkyleee** [comment]
Was able to fix by updating google services and repository  and configuring android sdk path via `local.properties` and fixed ios by dragging google services via xcode not finder

**Comment by auser** [comment]
So is this a resolved issue then for @iamkyleee and @tvtri96 ?

**Comment by iamkyleee** [comment]
i have resolved my issue. not sure about @tvtri96  :)

by the way i really appreciate this library. thank you so much 👍  @auser

**Comment by henrycity** [comment]
@iamkyleee : Can you tell it clearer? I do not understand it fully? If you have a picture, it would be very great.
1. Android: Do you mean that I have to update google services and repository in Genymotion? Also, what do you mean configure android sdk path by local.properties?
2. iOS: Which file is the google services? And how can I drag it? As I am not used to xCode, can you show me a picture?

**Comment by henrycity** [comment]
@auser : My error on iOS is the same with this one. [https://github.com/fullstackreact/FirestackApp/issues/7](https://github.com/fullstackreact/FirestackApp/issues/7)

**Comment by henrycity** [comment]
I manage to fix the error on Android by updating `gradle-wrapper.properties` file.
Change gradle version from 2.4 to 2.10
`distributionUrl=https\://services.gradle.org/distributions/gradle-2.10-all.zip`
