### ISSUE TITLE
DCTAuthAccount.h file not found

### ISSUE THREAD

**Issue by tam-borine** [fullstackreact/FirestackApp#6]
I cloned this project and installed dependencies and opened in XCode and got this error "DCTAuthAccount.h file not found". I searched for it and found in the Podfile DCTAuth and searched the repo for the file and can't seem to find exactly it. Have I missed something?

https://github.com/danielctull/DCTAuth/search?utf8=%E2%9C%93&q=DCTAuthAccount.h&type=Code

**Comment by esutton** [comment]
+1

I cannot figure this out where DCTAuthAccount.h is found either?

**Comment by Arelav** [comment]
react-native link will install it with pods but removes firebase

**Comment by esutton** [comment]
@Arelav Can you recommend a work-around ?

**Comment by auser** [comment]
Yes, you can just manually add the pod to the `Podfile` rather than let it overwrite the firestack one.

**Comment by natsu90** [comment]
Anyone who has no clue like me,

Add below line
```
pod 'DCTAuth', :git => 'https://github.com/danielctull/DCTAuth.git'
``` 
to `ios/Podfile` file right after `# Pods for FirestackApp` comment
