### ISSUE TITLE
“FirestackApp.entitlements” couldn’t be opened because there is no such file.  - but there is...

### ISSUE THREAD

**Issue by tam-borine** [fullstackreact/FirestackApp#8]
Weird...I can see the file right there in my tree of files on the left...
<img width="1274" alt="screen shot 2016-12-24 at 12 09 12" src="https://cloud.githubusercontent.com/assets/13587601/21466940/2596047a-c9d2-11e6-9469-3e273c622cb2.png">

**Comment by auser** [comment]
Was that in the repo when you got it? I just ignored that, actually. Try rebuilding after deleting the file

**Comment by inkloop** [comment]
@auser Hello! After deleting and rebuilding, I have new issues (see attachment).![](https://i.imgsafe.org/ffac007f44.png)

**Comment by auser** [comment]
Solved it. Go to your build settings and empty the Entitlements value: 

![](http://d.pr/i/bGZT.png)
